### ISSUE TITLE
the plugin no longer works

### ISSUE THREAD

**Issue by DarkGeneral1** [MrAn0nym/Aliucord-Plugins#4]
hello,
I've been using the betterNSFWbypass plugin for around a month now, but suddenly, it stopped working without a warning, i have the plugin version on 1.0.3, if there's a working version we can try to install until the plugin gets fixed, please let us know,
thanks.

**Comment by MrAn0nym** [comment]
thanks for the report. Unfortunately this issue started appearing for some people, but not for me. I tried looking into it but since it doesn't produce any errors and i found no way to replicate it there nothing i can do atm :/
