### ISSUE TITLE
[BetterNSFWBypass] does not work after update 1.0.5

### ISSUE THREAD

**Issue by Rexxt** [MrAn0nym/Aliucord-Plugins#5]
Title. Additional screenshot included:
![Screenshot_2022-02-21-20-42-17-316_com aliucord](https://user-images.githubusercontent.com/40831463/155017581-7d6b3ec3-1d80-4e7a-8693-31466009d6ed.jpg)

**Comment by MrAn0nym** [comment]
Should be working now

**Comment by MrAn0nym** [comment]
my bad, now it actually should ^^
