### ISSUE TITLE
[Timestamps] Option to append the timestamp to clipboard rather than overwriting the clipboard

### ISSUE THREAD

**Issue by quexpexx** [MrAn0nym/Aliucord-Plugins#7]
The way I usually use timestamps is that I start typing a message on something to do at a specific time. Then, to use the timestamp feature and keep what I already typed up, I need to store the text somewhere else, like a note app or in a DM to a bot. Then, I have to use the timestamp feature, get the timestamp in my clipboard, go back to that old text I typed up and put the timestamp at the end, then copy everything again and send it.  

It would be useful if an option existed for the plugin to make it read the clipboard first, and append the timestamp to it, and then put the previous text along with the timestamp into the clipboard.

**Comment by MrAn0nym** [comment]
Would the message option in v1.0.7 work as well?

**Comment by quexpexx** [comment]
Yes, the message option is fine, as it stops me from having to save the message somewhere else and then manually append the timestamp to it. Thank you!
